# Generated by Django 4.1.2 on 2022-11-02 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appt_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='rest', max_length=30),
            preserve_default=False,
        ),
    ]
